/*
 * Simple Core System API
 *
 * Moov Accounts is an HTTP service which represents both a general ledger and chart of accounts for customers. The service is designed to abstract over various core systems and provide a uniform API for developers.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreateTransaction struct for CreateTransaction
type CreateTransaction struct {
	Lines []TransactionLine `json:"lines,omitempty"`
}
