/*
 * Simple Core System API
 *
 * Moov Accounts is an HTTP service which represents both a general ledger and chart of accounts for customers. The service is designed to abstract over various core systems and provide a uniform API for developers.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountError struct for AccountError
type AccountError struct {
	// An error message describing the problem intended for humans.
	Error string `json:"error"`
}
