/*
 * Simple Core System API
 *
 * Moov Accounts is an HTTP service which represents both a general ledger and chart of accounts for customers. The service is designed to abstract over various core systems and provide a uniform API for developers.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateAccount struct {
	// Customer ID associated with accounts
	CustomerID string `json:"customerID"`
	// Initial balance of account in USD cents. This amount is to be deposited from an account at another Financial Institution or in-person (i.e. cash) on account creation.
	Balance int32 `json:"balance"`
	// Caller defined label for this account.
	Name string `json:"name"`
	// Random number to be used as unique to distinguish this Account
	Number string `json:"number,omitempty"`
	// Product type of the account
	Type string `json:"type"`
}
