// Copyright 2019 The Moov Authors
// Use of this source code is governed by an Apache License
// license that can be found in the LICENSE file.

// Generated on 2019-01-21T01:29:19Z by adam, any modifications will be overwritten
package glcode

var glCodes = map[string]string{
	"0001": "Estimated cash receipts",
	"0002": "Estimated cash disbursements",
	"0003": "Estimated 25th month cash disbursements",
	"0004": "Estimated encumbrances",
	"0005": "Estimated unallotted FTEs",
	"0006": "Estimated accrued receipts",
	"0064": "Estimated contract expenditures",
	"0110": "Approved estimated FTEs",
	"0111": "Adjusted estimated FTEs",
	"0120": "Actual FTEs",
	"0130": "Accrued FTEs",
	"0139": "Receivable liquidations",
	"0140": "FTE liquidations",
	"0159": "Liability liquidations",
	"0311": "Adjusted estimated revenue",
	"0611": "Approved unallotted",
	"0612": "Adjusted unallotted",
	"0613": "Adjusted unallotted",
	"0621": "Approved allotments",
	"0622": "Adjusted allotments",
	"0623": "Adjusted allotments",
	"0631": "Approved reserve",
	"0632": "Adjusted reserve",
	"0633": "Adjusted reserve",
	"0651": "Federal cost allocation expenditures",
	"0910": "Budgetary control",
	"0995": "Expenditure control",
	"0998": "Statistical clearing",
	"1120": "Undeposited Local Cash",
	"1130": "Petty Cash",
	"1150": "Cash with Fiscal Agents",
	"1206": "Investments with Local Government Investment Pool",
	"1209": "Short-Term Portion of Long-Term Investments",
	"1210": "Investments",
	"1215": "Investments under Reverse Repurchase Agreements",
	"1216": "Collateral held under Securities Lending Agreements",
	"1219": "Investments in Commingled Trust Funds (SIB Only)",
	"1220": "Unamortized Premiums on Investments",
	"1230": "Unamortized Discounts on Investments",
	"1240": "Restricted Cash and Investments - Noncurrent",
	"1271": "Commingled Trust Funds Investments (SIB Only)",
	"1272": "Commingled Trust Funds Unamortized Premiums on Investments (SIB Only)",
	"1273": "Commingled Trust Funds Unamortized Discounts on Investments (SIB Only)",
	"1278": "Commingled Trust Funds Valuation Allowance - Investments (SIB Only)",
	"1280": "Valuation Allowance - Investments",
	"1312": "Accounts Receivable",
	"1313": "Notes Receivable",
	"1314": "Loans Receivable",
	"1315": "Commingled Trust Funds Interest Receivable (SIB Only)",
	"1316": "Interest and Dividends Receivable",
	"1317": "Other Interest Receivable",
	"1318": "Unbilled Receivables",
	"1319": "Other Receivables",
	"1320": "Donations/Pledges Receivable",
	"1323": "Investment Trades Pending Receivable",
	"1324": "Salaries and Fringe Benefits Receivable",
	"1328": "Tax Liens Receivable",
	"1341": "Allowance for Uncollectible Taxes Receivable",
	"1342": "Allowance for Uncollectible Accounts Receivable",
	"1343": "Allowance for Uncollectible Notes Receivable",
	"1344": "Allowance for Uncollectible Loans Receivable",
	"1346": "Allowance for Uncollectible Interest Receivable on Investments",
	"1347": "Allowance for Uncollectible Other Interest Receivable",
	"1348": "Allowance for Uncollectible Tax Liens Receivable",
	"1349": "Allowance for Uncollectible Other Receivables",
	"1350": "Due from Other Funds - Advances",
	"1351": "Due from Federal Government",
	"1352": "Due from Other Governments",
	"1353": "Due from Other Funds",
	"1354": "Due from Other Agencies",
	"1355": "Due from Other Funds - Pooled Cash and Investments",
	"1359": "Due from Component Units",
	"1382": "L & I Self-Insurance Receivables",
	"1383": "Travel Advances",
	"1415": "Donated Inventories",
	"1420": "Merchandise Inventories",
	"1430": "Work-in-Process Inventories",
	"1440": "Raw Materials Inventories",
	"1450": "Livestock",
	"1611": "Taxes Receivable",
	"1614": "Loans Receivable",
	"1615": "Allowance for Forgivable LoansNonprofits",
	"1619": "Other Receivables",
	"1620": "Donations/Pledges Receivable",
	"1629": "PresentValue Allowance (SAC Only)",
	"1641": "Allowance for Uncollectible Taxes Receivable",
	"1644": "Allowance for Uncollectible Loans Receivable",
	"1649": "Allowance for Uncollectible Other Receivables",
	"1652": "Due from Other Governments",
	"1653": "Due from Other Funds",
	"1654": "Due from Other Agencies",
	"1655": "Allowance for Forgivable LoansOther Governments",
	"1659": "Due from Component Units",
	"1667": "Due from Other Funds - Internal Lending (UW Only)",
	"1820": "Amount to be Provided for Retirement of Long-Term Obligations",
	"1911": "Unamortized Discounts on Certificates of Participation",
	"1919": "Other Noncurrent Assets",
	"1950": "Investment in Joint Ventures",
	"1960": "Restricted NetPension Asset",
	"1971": "DeferredOutflows on COP Refundings",
	"1972": "DeferredOutflows on Bond Refundings",
	"1973": "Deferred Outflows on Hedging Derivatives",
	"1974": "Deferred Outflows onPensions",
	"1975": "Deferred Outflows on Other Postemployment Benefits",
	"2120": "Transportation Infrastructure - Modified Approach",
	"2130": "Art Collections, Library Reserve Collections, and Museum and Historical Collections",
	"2140": "IntangibleAssets with Indefinite Useful Lives",
	"2220": "Allowance for Depreciation - Buildings and Building Improvements",
	"2320": "Allowance for Depreciation - Improvements other than Buildings",
	"2350": "Leasehold Improvements",
	"2360": "Allowance for Depreciation - Leasehold Improvements",
	"2370": "Infrastructure",
	"2380": "Allowance for Depreciation - Infrastructure",
	"2420": "Allowance for Depreciation - Furnishings and Equipment",
	"2430": "Library Resources",
	"2440": "Allowance for Depreciation - Library Resources",
	"2450": "Art Collections, Library Reserve Collections, and Museum and Historical Collections",
	"2460": "Allowance for Depreciation - Art Collections, Library Reserve Collections, and Museum and Historical Collections",
	"2470": "Intangible Assets withDefinite Useful Lives",
	"2480": "Allowance for Amortization –Intangible Assets",
	"3198": "Estimated Revenue - Original",
	"3210": "Cash Revenues",
	"3213": "Gains and Losses on Sales of Capital Assets",
	"3215": "Immaterial Adjustments to Prior Periods",
	"3220": "Noncash Revenues",
	"3221": "Other Financing Sources",
	"3225": "Revenue Adjustments/Eliminations (GAAP)",
	"3260": "Estimated Accrued Revenues",
	"4315": "Warrants Outstanding (OST Only)",
	"4320": "Beginning Treasury Cash Balance Administrating Agency (OFM Only)",
	"4325": "Beginning Treasury Cash Balance - Agency",
	"5112": "Interest Payable",
	"5113": "Claims and Judgments Payable",
	"5114": "Annuities Payable (LOT Only)",
	"5115": "Contracts Payable",
	"5116": "Retained Percentages Payable",
	"5117": "Construction Contracts Payable",
	"5118": "Current Benefits Claims Payable",
	"5119": "Employee Insurance Benefits Payable",
	"5122": "Matured Interest Payable",
	"5123": "Investment Trades Pending Payable",
	"5124": "Accrued Salaries and Fringe Benefits Payable",
	"5125": "Accrued Vacation Leave Payable",
	"5126": "Accrued Prizes Payable (LOT Only)",
	"5127": "Accrued Sick Leave Payable",
	"5128": "Accrued Compensatory Time Payable",
	"5130": "Due to Fiscal Agents",
	"5140": "Due to Terminated Employees",
	"5145": "Due to Deceased Employees' Estates",
	"5148": "L & I Retrospective Program Estimated Premium Refund Payables",
	"5149": "L & I Claims Administration Expense Payable",
	"5151": "Due to Federal Government",
	"5152": "Due to Other Governments",
	"5153": "Due to Other Funds",
	"5154": "Due to Other Agencies",
	"5155": "Due to Other Funds - Pooled Cash and Investments",
	"5156": "Due to Other Funds - Local Government Investment Pool (OST Only)",
	"5157": "Due to Owner Funds - Commingled Trust Funds Investment Income (SIB Only)",
	"5158": "Due to Department of Revenue - Taxes",
	"5159": "Due to Primary Government",
	"5162": "Revenue Bonds Payable",
	"5163": "Limited Obligation Bonds Payable",
	"5164": "Zero-Coupon Bonds Payable",
	"5165": "Accreted Interest Payable - Zero-Coupon Bonds",
	"5167": "General Revenue Bonds Payable - Internal Lending (UW Only)",
	"5169": "Other Bonds Payable",
	"5172": "Lease-Purchase Agreements Payable",
	"5173": "Certificates of Participation/Notes Payable",
	"5180": "Paid Family and Medical Leave Deductions Payable",
	"5182": "EBT Authorized Benefits Payable",
	"5183": "Liability for Expunged EBT Benefits",
	"5184": "Tuition Benefits Payable",
	"5185": "Net Pension Liability",
	"5186": "Other Postemployment Benefits Liability - Short Term",
	"5187": "Industrial Insurance and Medical Aid Deductions Payable",
	"5188": "Savings Bond Deductions Payable",
	"5189": "Garnishment Deductions Payable",
	"5190": "Unearned Revenues",
	"5191": "Deposits Payable",
	"5192": "UnavailableRevenues – Short-term",
	"5193": "Liability for Unclaimed Property Refunds",
	"5194": "Liability for Canceled Warrants/Checks",
	"5195": "Deferred Expenditure Recoveries",
	"5196": "Obligations under Reverse Repurchase Agreements",
	"5197": "Obligations under Securities Lending Agreements",
	"5198": "Loans Payable",
	"5199": "Other Liabilities",
	"5213": "Claims and Judgments Payable",
	"5216": "Retained Percentages Payable",
	"5225": "Accrued Vacation Leave Payable",
	"5226": "Annuities Payable (LOT Only)",
	"5227": "Accrued Sick Leave Payable",
	"5228": "Accrued Compensatory Time Payable",
	"5247": "Liability for Deferred Compensation",
	"5252": "Due to Other Governments",
	"5253": "Due to Other Funds",
	"5254": "Due to Other Agencies",
	"5259": "Due to Primary Government",
	"5262": "Revenue Bonds Payable",
	"5263": "Limited Obligation Bonds Payable",
	"5264": "Zero-Coupon Bonds Payable",
	"5265": "DeferredInflows on Pensions",
	"5266": "DeferredInflows on COP Refundings",
	"5267": "GeneralRevenue Bonds Payable – Internal Lending (UW Only)",
	"5268": "DeferredInflows on Bond Refundings",
	"5269": "Other Bonds Payable",
	"5272": "Lease-Purchase Agreements Payable",
	"5273": "Certificates of Participation/Notes Payable",
	"5282": "Other Postemployment Benefits Obligation",
	"5283": "DeferredInflows on Hedging Derivatives",
	"5284": "Tuition Benefits Payable",
	"5285": "Benefits Claims Payable",
	"5286": "Claims Administration Expense Payable (L&I Only)",
	"5287": "Pollution Remediation Obligation",
	"5288": "Deferred Inflows on Irrevocable Split-Interest Agreements",
	"5290": "Unearned Revenues",
	"5291": "Deposits Payable",
	"5292": "UnavailableRevenues – Long-term",
	"5293": "Liability for Unclaimed Property Refunds",
	"5294": "Deferred Inflows on Other Postemployment Benefits",
	"5297": "Fees Payable",
	"5298": "Other Obligations – Capital Related",
	"5299": "Other Obligations",
	"5920": "Unamortized Premiums on COPs Sold",
	"6215": "Estimated Unallotted Expenses",
	"6510": "Cash Expenditures/Expenses",
	"6511": "Depreciation/AmortizationExpense",
	"6512": "Amortization Expense",
	"6514": "Capital Asset Acquisitions by Lease Purchase Agreements or Certificates of Participation",
	"6515": "Bad Debts Expense",
	"6516": "Cost of Goods Sold",
	"6525": "Expense Adjustments/Eliminations (GAAP)",
	"6560": "Estimated Accrued Expenditures/Expenses",
	"6591": "Depreciation/AmortizationExpense (General Capital Assets Subsidiary Account Only)",
	"6592": "Interest Expense (General Long-Term Obligations Subsidiary Account Only)",
	"6593": "Amortization Expense (GeneralLong-Term Obligations Subsidiary Account Only)",
	"6594": "Pollution Remediation Expense (General Long-Term Obligations Subsidiary Account Only)",
	"6595": "Other Postemployment Benefits Expense (General Long-Term Obligations Subsidiary Account Only)",
	"6596": "Excess Contributions for Pension Benefits (General Long-Term Subsidiary Account Only)",
	"6597": "CapitalAsset Adjustment (General Capital Assets Subsidiary Account Only)",
	"6598": "PensionExpense",
	"7120": "Warrants In-Process/ACH (Automated Clearing House) Payments In-Process",
	"7130": "Warrant Cancellations In-Process",
	"7140": "Journal Vouchers In-Process",
	"9110": "Nonspendable Permanent FundPrincipal",
	"9112": "Nonspendable Permanent Funds– Unrealized Gain/Loss",
	"9120": "Nonspendable ConsumableInventories",
	"9130": "NonspendableStudent Loans Receivable",
	"9131": "NonspendableReceivables – Long-Term",
	"9230": "Restrictedfor Higher Education",
	"9231": "Restricted for Permanent Funds - Realized Investment Losses",
	"9232": "Restrictedfor Education",
	"9234": "Restrictedfor Transportation",
	"9235": "Restricted for Bond Covenants",
	"9238": "Restrictedfor Other Purposes",
	"9240": "Restrictedfor Human Services",
	"9242": "Restrictedfor Wildlife and Natural Resources",
	"9244": "Restrictedfor Local Grants and Loans",
	"9246": "Restrictedfor School Construction",
	"9248": "Restrictedfor State Facilities",
	"9250": "Restrictedfor Budget Stabilization",
	"9252": "Restrictedfor Debt Service",
	"9255": "Restrictedfor Cash and Investments with Escrow Agents and Trustees",
	"9260": "Restricted for Pollution Remediation Liabilities",
	"9270": "Restricted for Unspent Bond Proceeds",
	"9271": "Restrictedfor Operations and Maintenance Reserve",
	"9272": "Restrictedfor Repair and Replacement Reserve",
	"9273": "Restrictedfor Revenue Stabilization",
	"9274": "Restrictedfor Unspent GARVEE Bond Proceeds",
	"9275": "Restricted for Deferred Sales Tax",
	"9283": "Restrictedfor Third Tier Debt Service",
	"9284": "Restricted for Fourth Tier Debt Service",
	"9285": "Restricted for GARVEE Bond Debt Service",
	"9310": "Committedfor Higher Education",
	"9311": "Committedfor Education",
	"9320": "Committedfor Transportation",
	"9321": "Committedfor Other Purposes",
	"9323": "Committedfor Human Services",
	"9324": "Committedfor Wildlife and Natural Resources",
	"9325": "Committedfor Local Grants and Loans",
	"9330": "Committedfor State Facilities",
	"9340": "Committedfor Debt Service",
	"9350": "Net Investmentin Capital Assets(OFM Only)",
	"9370": "Assignedfor Working Capital (OFM Only)",
	"9372": "Assignedfor Other Purposes",
	"9390": "Unassigned",
	"9400": "Accumulated Earnings (Losses)",
	"9410": "Restricted Net Position",
	"9450": "Unrestricted Net Position (OFM Only)",
	"9510": "Reservedfor Encumbrances",
	"9513": "Reservedfor Encumbrances for Reappropriated Capital Appropriations",
	"9514": "Reservedfor Encumbrances for Continuing Operating Expenditure Authority",
	"9545": "Restricted for Unemployment Compensation",
	"9546": "Restricted for Pensions",
	"9550": "Restricted for Pensions",
	"9551": "Restricted for Deferred Compensation Participants",
	"9554": "Restricted for LocalGovernment Pooled Investments Participants",
	"9601": "Restricted for Members (DRS Only)",
	"9603": "Restricted for Benefits (DRS Only)",
	"9604": "Restrictedfor Benefits - Medical (DRS Only)",
	"9607": "Restrictedfor Higher Education Retirement Plan SupplementalBenefits (DRS Only)",
	"9608": "Restricted for Members Defined Contributions - SIB (DRS Only)",
	"9609": "Restricted for Members Defined Contributions - Self-Directed (DRS Only)",
	"9720": "PriorPeriod Material Corrections (OFM Only)",
	"9721": "FundType Reclassification Changes (OFM Only)",
	"9722": "AccountingPolicy Changes (OFM Only)",
	"9723": "CapitalAsset Policy Changes",
	"9920": "Current Period Clearing(All Fund Types Except Subsidiary Accounts)",
	"9940": "Reserve Clearing(DRS Only)",
	"9998": "Beginning Balance Clearing(OFM Only)",
}
